name: AI Code Review

on:
  pull_request_target:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Instalar dependências
        run: npm install openai @octokit/rest

      - name: Rodar análise da IA
        run: node ai-review.js
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
